- hosts: dev
  remote_user: zulfi
  gather_facts: no
  become: true
  tasks:
  - name: test
    shell: whoami
  - name: Ansible create file if it doesn't exist example
    command: touch /home/test.txt

    